#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
#

service: serverless-inventory-acl
frameworkVersion: "3"

plugins:
  - serverless-plugin-datadog

custom:
  serviceName: JavaInventoryAcl
  datadog:
    apiKeySecretArn: ${param:DD_API_KEY_SECRET_ARN}
    site: ${param:DD_SITE}
    env: ${sls:stage}
    service: ${self:custom.serviceName}
    version: 65
    # Use this property with care in production to ensure PII/Sensitive data is not stored in Datadog
    captureLambdaPayload: true
    propagateUpstreamTrace: true

provider:
  name: aws
  runtime: java21
  memorySize: 2048
  timeout: 29
  logRetentionInDays: 1
  environment:
    ENV: ${sls:stage}
    POWERTOOLS_SERVICE_NAME: ${self:custom.serviceName}
    POWERTOOLS_LOG_LEVEL: 'INFO'
    DD_LOGS_INJECTION: "true"
    MAIN_CLASS: com.inventory.acl.FunctionConfiguration
    AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${param:DD_API_KEY_SECRET_ARN}
        - Effect: Allow
          Action:
            - sns:Publish
          Resource:
            - !Ref NewProductAddedTopic

functions:
  publishPublicEvents:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    environment:
      PRODUCT_ADDED_TOPIC_ARN: !Ref NewProductAddedTopic
      DD_SERVICE_MAPPING: !Sub "lambda_sqs:${JavaInventoryProductCreatedEventQueue.QueueName}"
      spring_cloud_function_definition: handleProductCreatedEvent
    package:
      artifact: ./inventory-acl/target/com.inventory.acl-0.0.1-SNAPSHOT-aws.jar
      individually: true
    events:
      - sqs:
          arn:
            Fn::GetAtt: [JavaInventoryProductCreatedEventQueue, Arn]

resources:
  Resources:
    NewProductAddedTopic:
      Type: AWS::SNS::Topic
      Properties:
        TopicName: !Sub "JavaInventoryNewProductAddedTopic-${sls:stage}"
    
    NewProductAddedTopicArn:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /java/inventory/new-product-added-topic
        Type: String
        Value: !Ref NewProductAddedTopic
    
    NewProductAddedTopicName:
      Type: AWS::SSM::Parameter
      Properties:
        Name: /java/inventory/new-product-added-topic-name
        Type: String
        Value: !GetAtt NewProductAddedTopic.TopicName

    JavaInventoryProductCreatedEventDLQ:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "JavaInventoryProductCreatedEventDLQ-${sls:stage}"

    JavaInventoryProductCreatedEventQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: !Sub "JavaInventoryProductCreatedEventQueue-${sls:stage}"
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - "JavaInventoryProductCreatedEventDLQ"
              - "Arn"
          maxReceiveCount: 3

    ProductCreatedEventRule:
      Type: AWS::Events::Rule
      Properties:
        EventBusName: "${ssm:/java/shared/event-bus-name}"
        Name: inventory-product-created
        State: ENABLED
        EventPattern:
          source:
            - !Sub "${sls:stage}.products"
          detail-type:
            - "product.productCreated.v1"
        Targets:
          - Id: ProductCreatedEventQueue
            Arn: !GetAtt JavaInventoryProductCreatedEventQueue.Arn

    SnsToQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      Properties: 
        Queues:
          - !Ref JavaInventoryProductCreatedEventQueue
        PolicyDocument: 
          Version: '2012-10-17'
          Statement:
            - Sid: allow-eb-send-message-messages
              Effect: Allow
              Principal:
                Service: "events.amazonaws.com"
              Resource: !GetAtt JavaInventoryProductCreatedEventQueue.Arn
              Action: SQS:SendMessage