#
# Unless explicitly stated otherwise all files in this repository are licensed
# under the Apache License Version 2.0.
# This product includes software developed at Datadog (https://www.datadoghq.com/).
# Copyright 2024 Datadog, Inc.
# 

service: serverless-inventory-ordering-service
frameworkVersion: "3"

plugins:
  - serverless-step-functions
  - serverless-plugin-datadog

custom:
  serviceName: JavaInventoryOrderingService
  datadog:
    apiKeySecretArn: ${param:DD_API_KEY_SECRET_ARN}
    site: ${param:DD_SITE}
    env: ${sls:stage}
    service: ${self:custom.serviceName}
    version: 65
    # Use this property with care in production to ensure PII/Sensitive data is not stored in Datadog
    captureLambdaPayload: true
    propagateUpstreamTrace: true

provider:
  name: aws
  runtime: java21
  memorySize: 2048
  timeout: 29
  logRetentionInDays: 1
  environment:
    ENV: ${sls:stage}
    POWERTOOLS_SERVICE_NAME: ${self:custom.serviceName}
    POWERTOOLS_LOG_LEVEL: 'INFO'
    DD_LOGS_INJECTION: "true"
    MAIN_CLASS: com.inventory.ordering.FunctionConfiguration
    AWS_LAMBDA_EXEC_WRAPPER: /opt/datadog_wrapper
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - secretsmanager:GetSecretValue
          Resource: ${param:DD_API_KEY_SECRET_ARN}
        - Effect: Allow
          Action:
            - states:StartExecution
          Resource:
            - !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:inventoryOrderingWorkflow${sls:stage}

functions:
  startOrderWorkflow:
    handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest
    environment:
      DD_SERVICE_MAPPING: !Sub "lambda_sns:${ssm:/java/inventory/new-product-added-topic-name}"
      ORDERING_SERVICE_WORKFLOW_ARN: !Sub arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:inventoryOrderingWorkflow${sls:stage}
      spring_cloud_function_definition: handleNewProductAdded
    package:
      artifact: ./inventory-ordering-service/target/com.inventory.ordering-0.0.1-SNAPSHOT-aws.jar
      individually: true
    events:
      - sns: ${ssm:/java/inventory/new-product-added-topic}

stepFunctions:
  stateMachines:
    inventoryOrderingWorkflow:
      name: inventoryOrderingWorkflow${sls:stage}
      definition: ${file(cdk/src/main/java/com/cdk/inventory/ordering/workflows/workflow.sample.asl.json)}
      loggingConfig:
        level: ALL
        includeExecutionData: true
        destinations:
          - Fn::GetAtt: [InventoryOrderingServiceLogGroup, Arn]
      tags:
          DD_ENHANCED_METRICS: "true"
          DD_TRACE_ENABLED: "true"

resources:
  Resources:
    InventoryOrderingServiceLogGroup: 
      Type: AWS::Logs::LogGroup
      Properties: 
        RetentionInDays: 1
        LogGroupName: !Sub "/aws/vendedlogs/states/JavaInventoryOrderingServiceLogGroup-${sls:stage}"